
server:
  5000

cloud:
  aws:
    region:
        static: ap-northeast-2
    credentials:
        access-key: #
        secret-key: #

    stack:
        auto: false

    s3:
      bucket: #

jwt:
  access:
    secret: #
    expiration: 36000000

  refresh:
    secret: #
    expiration: 204800000

spring:

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: usk883135@gmail.com #?? ??
#    password: vwwvejgrqsalzcym #? ????
#    protocol : smtp #??? ???
#    properties:
#      mail:
#        protocol : smtp #??? ???
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 20000
#          timeout: 20000
#          writetimeout: 20000
#    auth-code-expiration: 900000 # 15?

---

spring:
  config:
    activate:
      on-profile: local

#  datasource:
#    url: jdbc:mysql://your-rds-endpoint:3306/your-db-name
#    username: admin
#    password: tacobackend
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update  # ??: ?? ????? validate ??
#    show-sql: true
#    open-in-view: false

#  redis:
#      #host: taco-3-team1-diary-redis-7f0usp.serverless.apn2.cache.amazonaws.com
#      host : localhost
#      port: 6379 #6379
#      ssl: false
#      password :

#  #mongoDb ?? ??
#  data :
#    mongodb :
#      uri : mongodb+srv://springboot_user:hi882735@springboot.jbtz1.mongodb.net/?retryWrites=true&w=majority&appName=springBoot
#      database : springBootDocuments # db ??

---

spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: jdbc:mysql://your-rds-endpoint:3306/your-db-name
#    username: admin
#    password: tacobackend
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update  # ??: ?? ????? validate ??
#    show-sql: true
#    open-in-view: false

#  redis:
#      #host: taco-3-team1-diary-redis-7f0usp.serverless.apn2.cache.amazonaws.com
#      host : localhost
#      port: 6379 #6379
#      ssl: false
#      password :

#  #mongoDb ?? ??
#  data :
#    mongodb :
#      uri : mongodb+srv://springboot_user:hi882735@springboot.jbtz1.mongodb.net/?retryWrites=true&w=majority&appName=springBoot
#      database : springBootDocuments # db ??



---

spring:
  config:
    activate:
      on-profile: test

  # test inmemory db
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto : create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect