version: '3.8'

services: 
 
  # RabbitMQ (Amazon MQ 대체)
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: tacohub-rabbitmq-local
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'   # AMQP
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      timeout: 20s
      retries: 10